DOMAIN = "powerbaas"

CONF_DEVICE_TYPE = "device_type"

DEVICE_TYPE_P1_METER = "p1_meter"
DEVICE_TYPE_BOILER_CONTROLLER = "boiler_controller"
DEVICE_TYPES = [DEVICE_TYPE_P1_METER, DEVICE_TYPE_BOILER_CONTROLLER]
